import { Category, FilterItem, Product } from '../types';

export const products: Product[] = [
  {
    id: 'pubg',
    name: 'PUBG MOBILE',
    subtitle: 'شدّات ببجي موبايل الرسمية',
    category: 'games',
    price: 0.99,
    unit: '60 UC',
    icon: 'game-controller',
    color: '#e5a00d',
    tag: 'الأكثر طلبًا',
    description: 'شحن فوري لشدات ببجي موبايل عن طريق معرّف اللاعب (Player ID) مباشرة بدون الحاجة لكلمة المرور.',
  },
  {
    id: 'cod',
    name: 'Call of Duty: Mobile',
    subtitle: 'نقاط كول أوف ديوتي CP',
    category: 'games',
    price: 1.49,
    unit: '80 CP',
    icon: 'game-controller',
    color: '#3498db',
    tag: 'شحن مباشر',
    description: 'شحن نقاط كول أوف ديوتي موبايل الرسمية لتفعيل الرويال باس وشراء الصناديق والأسلحة المميزة.',
  },
  {
    id: 'apex',
    name: 'Apex Legends Mobile',
    subtitle: 'عملات أبيكس ليجندز الرسمية',
    category: 'games',
    price: 9.99,
    unit: '1,000 Coins',
    icon: 'game-controller',
    color: '#e74c3c',
    tag: 'اختيار اللاعبين',
    description: 'شحن عملات Apex Legends المعتمدة لكافة الحسابات في الشرق الأوسط والعالم.',
  },
  {
    id: 'stumble',
    name: 'Stumble Guys',
    subtitle: 'جواهر ستامبل غايز',
    category: 'games',
    price: 1.99,
    unit: '250 Gems',
    icon: 'game-controller',
    color: '#9b59b6',
    description: 'جواهر ستامبل غايز الأصلية لشراء السكنات والرقصات والبطاقات الحصرية.',
  },
  {
    id: 'spotify',
    name: 'Spotify Premium',
    subtitle: 'موسيقاك، بلا حدود وبدون إعلانات',
    category: 'apps',
    price: 3.99,
    unit: 'شهر واحد',
    icon: 'musical-notes',
    color: '#39a567',
    tag: 'اشتراك فوري',
    description: 'استمتع بمكتبة موسيقية لا حصر لها بدقة صوت فائقة وخاصية الاستماع دون اتصال بالإنترنت.',
  },
  {
    id: 'discord',
    name: 'Discord Nitro',
    subtitle: 'ارتقِ بتجربتك مع ديسكورد',
    category: 'apps',
    price: 4.99,
    unit: 'شهر واحد',
    icon: 'logo-discord',
    color: '#888bed',
    tag: 'مفضّل للمجتمعات',
    description: 'تفعيل اشتراك Discord Nitro متضمنًا دعم السيرفرات واستخدام الإيموجيات المخصصة في أي مكان.',
  },
  {
    id: 'steam',
    name: 'Steam Gift Card',
    subtitle: 'بطاقة ستيم الرقمية المباشرة',
    category: 'cards',
    price: 10.0,
    unit: '$10 USD',
    icon: 'logo-steam',
    color: '#788fae',
    tag: 'كود فوري',
    description: 'بطاقة رصيد ستيم حساب عالمي وأمريكي لشراء أحدث الألعاب والإضافات على متجر Steam.',
  },
  {
    id: 'playstation',
    name: 'PlayStation Store',
    subtitle: 'بطاقة بلايستيشن • حساب أمريكي',
    category: 'cards',
    price: 10.0,
    unit: '$10 USD',
    icon: 'logo-playstation',
    color: '#5781bf',
    description: 'رصيد رسمي لمتجر PlayStation Network لشراء ألعاب PS5 وPS4 واشتراكات PS Plus.',
  },
  {
    id: 'instagram',
    name: 'متابعو Instagram',
    subtitle: 'امنح حسابك حضورًا أكبر وانتشارًا أسرع',
    category: 'instagram',
    price: 1.8,
    unit: '100 متابع',
    icon: 'logo-instagram',
    color: '#c381a4',
    tag: 'الأكثر طلبًا',
    description: 'زيادة متابعين انستغرام بجودة عالية وسرعة آمنة بدون الحاجة لأي كلمات مرور. الحساب يجب أن يكون عامًا.',
  },
  {
    id: 'instagram-likes',
    name: 'إعجابات Instagram',
    subtitle: 'تفاعل أكثر مع منشوراتك وريلز',
    category: 'instagram',
    price: 0.9,
    unit: '100 إعجاب',
    icon: 'heart-outline',
    color: '#c381a4',
    description: 'إعجابات سريعة لمنشوراتك أو مقاطع الريلز لدعم خوارزميات الانتشار وظهور المحتوى في Explore.',
  },
  {
    id: 'tiktok',
    name: 'متابعو TikTok',
    subtitle: 'خطوتك التالية نحو الانتشار والترند',
    category: 'tiktok',
    price: 1.5,
    unit: '100 متابع',
    icon: 'logo-tiktok',
    color: '#7fbabc',
    tag: 'ترند تيك توك',
    description: 'زيادة متابعين تيك توك لحسابك للوصول إلى شروط البث المباشر وزيادة المصداقية والتفاعل.',
  },
  {
    id: 'tiktok-views',
    name: 'مشاهدات TikTok',
    subtitle: 'وصول أوسع لفيديوهاتك وFor You',
    category: 'tiktok',
    price: 0.5,
    unit: '1,000 مشاهدة',
    icon: 'play-circle-outline',
    color: '#7fbabc',
    description: 'مشاهدات فائقة السرعة لفيديوهات TikTok للمساعدة في الصعود إلى صفحة الاكسبلور (For You).',
  },
  {
    id: 'youtube',
    name: 'مشاهدات YouTube',
    subtitle: 'دع محتواك يصل إلى جمهور أوسع',
    category: 'youtube',
    price: 2.5,
    unit: '1,000 مشاهدة',
    icon: 'logo-youtube',
    color: '#c57373',
    tag: 'سرعة وثبات',
    description: 'مشاهدات آمنة لقنوات اليوتيوب للمساعدة في تحقيق شروط تحقيق الدخل وتحسين ترتيب الفيديو في البحث.',
  },
  {
    id: 'facebook',
    name: 'إعجابات Facebook',
    subtitle: 'مجتمع يتفاعل مع صفحتك ومنشوراتك',
    category: 'facebook',
    price: 1.9,
    unit: '100 إعجاب',
    icon: 'logo-facebook',
    color: '#829dc6',
    description: 'إعجابات لصفحات وفيسبوك وبوستاتك العامة من حسابات نشطة.',
  },
  {
    id: 'x',
    name: 'متابعو X',
    subtitle: 'مساحة أوسع لأفكارك وتغريداتك',
    category: 'x',
    price: 3.5,
    unit: '100 متابع',
    icon: 'close',
    color: '#bcbcbc',
    description: 'متابعون حقيقيون لمنصة X (تويتر سابقاً) لدعم حسابك الشخصي أو التجاري وزيادة التفاعل.',
  },
];

export const categories: Category[] = [
  { id: 'games', name: 'شحن الألعاب', sub: 'جاهز للّعبة التالية؟', icon: 'game-controller-outline' },
  { id: 'apps', name: 'شحن التطبيقات', sub: 'اشتراكاتك المفضلة', icon: 'apps-outline' },
  { id: 'cards', name: 'بطاقات رقمية', sub: 'عالم من الخيارات', icon: 'card-outline' },
  { id: 'instagram', name: 'Instagram', sub: 'حضور يستحق الاهتمام', icon: 'logo-instagram' },
  { id: 'tiktok', name: 'TikTok', sub: 'خلك في الترند', icon: 'logo-tiktok' },
  { id: 'social', name: 'خدمات السوشيال', sub: 'انتشار بلا حدود', icon: 'share-social-outline' },
];

export const filters: FilterItem[] = [
  { id: 'all', name: 'جميع الخدمات' },
  ...categories,
  { id: 'youtube', name: 'YouTube' },
  { id: 'facebook', name: 'Facebook' },
  { id: 'x', name: 'X' },
];

export const isSocial = (category: string): boolean => {
  return ['instagram', 'tiktok', 'youtube', 'facebook', 'x', 'social'].includes(category);
};

export const money = (val: number): string => {
  return `$${(Number(val) || 0).toFixed(2)}`;
};

export const statusLabels: Record<string, string> = {
  review: 'قيد المراجعة',
  processing: 'قيد التنفيذ',
  completed: 'مكتمل',
  rejected: 'مرفوض',
};
